#!/usr/bin/env escript
%%! -pa ebin -pa deps/mochiweb/ebin

main(_) ->
    application:load(lockstep),
    application:ensure_all_started(ssl),
    inets:start(),
    {ok, Pid}  = gen_lockstep:start_link(lockstep_cb, "http://hermes:hermes@localhost:8080/domains", []),

    receive ok -> ok end.
